spring.application.name=data-server-springboot
# application.properties

# Connect to Docker PostgreSQL on localhost
spring.datasource.url=jdbc:postgresql://localhost:5432/anime_db

# Docker PostgreSQL credentials
spring.datasource.username=anime_user
spring.datasource.password=anime_pass

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080
